name: CI/CD Pipeline for React

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy-v3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image for v3
      run: |
        docker build -t vk2615/react-v3:latest -f ./react-v3/Dockerfile ./react-v3
        docker push vk2615/react-v3:latest
    - name: SSH into server and deploy to Docker Swarm (v3 only)
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Pull the latest image for v3 from DockerHub
          docker pull vk2615/react-v3:latest
          # Check if the v3 service exists, create it if not
          if ! docker service ls | grep -q "react-v3"; then
            echo "Creating v3 service on port 8080"
            docker service create --name react-v3 --replicas 2 -p 8080:80 vk2615/react-v3:latest
          else
            echo "v3 service already exists, updating it"
            docker service update --image vk2615/react-v3:latest react-v3
          fi 
