name: CI/CD Pipeline for React with Manual Rolling Update

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy-and-rollback:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (for multi-platform builds, if necessary)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 4: Build and push Docker image for v3
    - name: Build and push Docker image for v3
      run: |
        docker build -t vk2615/react-v3:$GITHUB_SHA -f ./react-v3/Dockerfile ./react-v3
        docker push vk2615/react-v3:$GITHUB_SHA

    # Step 5: Build and push Docker image for v4
    - name: Build and push Docker image for v4
      run: |
        docker build -t vk2615/react-v4:$GITHUB_SHA -f ./react-v4/Dockerfile ./react-v4
        docker push vk2615/react-v4:$GITHUB_SHA

    # Step 6: SSH into the remote server and deploy to Docker Swarm
    - name: SSH into server and deploy to Docker Swarm
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Pull the latest images from DockerHub directly to the remote server
          docker pull vk2615/react-v3:$GITHUB_SHA
          docker pull vk2615/react-v4:$GITHUB_SHA

          # Check if the v3 service exists and deploy it if not
          if ! docker service ls | grep -q "react-v3"; then
            echo "Creating v3 service"
            docker service create --name react-v3 --replicas 2 -p 4444:80 vk2615/react-v3:$GITHUB_SHA
          else
            echo "v3 service already exists"
          fi

          # Deploy v3 first (manual step)
          echo "Deployed v3 on the server."

          # After deploying v3, proceed to update the service to v4 (rolling update)
          echo "Performing rolling update to v4"
          docker service update --image vk2615/react-v4:$GITHUB_SHA react-v3

          # Optionally, check if v4 is deployed and confirm the rolling update
          docker service ls
