name: Rolling Update CI/CD Pipeline for React

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images for v3 (if v3 is being deployed)
      if: github.event.head_commit.message != 'Deploy v4'  # Only run if v4 is not mentioned
      run: |
        docker build -t vk2615/react-v3:$GITHUB_SHA -f ./react-v3/Dockerfile ./react-v3
        docker push vk2615/react-v3:$GITHUB_SHA

    - name: Build and push Docker images for v4 (if v4 is being deployed)
      if: github.event.head_commit.message == 'Deploy v4'  # Only run if v4 is being deployed
      run: |
        docker build -t vk2615/react-v4:$GITHUB_SHA -f ./react-v4/Dockerfile ./react-v4
        docker push vk2615/react-v4:$GITHUB_SHA
